### ISSUE TITLE
Is this possible to implement in both http.Server and https.Server?

### ISSUE THREAD

**Issue by shengLin-alex** [moebius-mlm/http-graceful-shutdown#3]
Since my express server implementation is not http, I am thinking about whether it can be implemented in https.Server?

the constructor would be like:
` public constructor(private server: http.Server | https.Server) {
        this.startWatchingServer();
}`

thank you very much!

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I've just pushed version `1.1.0` to the npm. Could you please tell me if it works for you?

By the way, I think that you could've just used the type coercion for the constructor argument as a workaround.

**Comment by shengLin-alex** [comment]
Hi, thanks for your support!
It works like a charm.

**Comment by slavafomin** [comment]
Great! Have a nice day ;)
